### ISSUE TITLE
email in comment

### ISSUE THREAD

**Issue by WarminkH** [njb170000/ChatbotProject#1]
In json.ccp you use a real email address, is there any specific reason why you use this email address

// the label cannot contain certain characters
	if (strchr(word, ' ') ||
		strchr(word, '\\') || strchr(word, '"') || strchr(word, '\'') || strchr(word, 0x7f) || strchr(word, '\n') // refuse illegal content
		|| strchr(word, '\r') || strchr(word, '\t')) return false;    // must be legal unescaped json content and safe CS content

	// "realemail@address.com" is not a valid JSON name
	// last part must be numbers
	char* end = word + n - 1;
	char* at = end;

**Comment by SwagataSe-Kore** [comment]
Hello @njb170000, this email id is specific to a customer of the Kore.ai platform. Please remove this. This would have come from the source but the source repo of ChatScript has it deleted now. ref: https://github.com/ChatScript/ChatScript/blob/master/SRC/json.cpp#L177
Please note that we have informed the GitHub support also and they recommended requesting you directly to remove this reference. Please extend your cooperation in this regard.
P.S: We see that @WarminkH already enquired about this so we are not creating a new issue.

**Comment by SwagataSe-Kore** [comment]
@WarminkH May I request you to edit/obfuscate the email id in your comment above? If this is updated in the source, through this comment it may be available to everyone. Thanks for your understanding.

**Comment by njb170000** [comment]
I went ahead and deleted the comment in the file.  I also edited WarminkH's comment on the issue to no longer have the email address in it.

**Comment by SwagataSe-Kore** [comment]
Thank you @njb170000
